In [1]:
import evolutionary_operator as eo
import torch
import benchmark_funs as bf

In [2]:
problem = bf.Sphere(3)
for i_s in eo.initialization_operators.strategies:
    i_strategy = i_s(problem)
    x = torch.zeros(2, 3)
    h = torch.zeros(2, 4)
    x,h,e = i_strategy(x, h)
    print(x)

tensor([[ 87.5232, -30.7827,  20.9177],
        [ 96.4026, -53.5012, -18.6543]])
tensor([[ 43.3651,  63.8642,  57.6104],
        [  6.0159, -36.0110, -22.2320]])
tensor([[ 20.5618, -11.5535,  -9.7155],
        [  2.3757,   5.2946,   3.7290]])
tensor([[ 2.9270, 10.9354, -0.3971],
        [-8.3762, 11.8897, 12.5600]])
tensor([[ 35.1843,  -2.9433, -16.1841],
        [ 15.4306,  54.5371,   1.9119]])
tensor([[ -13.5959,   51.5649, -100.0000],
        [-100.0000,   15.9120,   -6.4331]])
tensor([[-16.9481,  27.5839,  -4.8067],
        [ -4.6657,   2.1110,   1.0371]])
tensor([[  0.0000,   0.0000, -44.0071],
        [ -5.3343, -13.9536, -26.5578]])
tensor([[ 0.0000,  8.4083,  0.0000],
        [ 0.0000,  0.0000, -8.8641]])
tensor([[  0.0000,   0.0000,  12.0073],
        [ 26.3655, -16.9878,   4.8219]])
tensor([[  0.0000,   0.0000,   0.0000],
        [ 59.0276, -13.7544,  -0.1924]])


In [3]:
for m_s in eo.mutation_operators.strategies:
    m_strategy = m_s(problem)
    x = torch.zeros(2, 3)
    h = torch.ones(2, 4)
    x,h,e = m_strategy(x, h)
    print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.0538, -0.9565, -1.3491],
        [-0.3106, -0.1725, -0.0200]])
tensor([[ 2.7694,  1.3264, -0.1102],
        [-0.3125,  0.3648, -4.3289]])
tensor([[-0.0119,  2.6289,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [4]:
# hh = eo.abstract_operators.hyper_hyper_param_from_dict({'opponents_ratio':3/4})
for s_s in eo.selection_operators.strategies:
    # s_strategy = s_s(problem, hh)
    s_strategy = s_s(problem)
    x = torch.zeros(2, 3)
    h = torch.ones(2, 4)
    x,h,e = s_strategy(x, h)
    print(x)

tensor([[0., 0., 0.]])
tensor([[0., 0., 0.]])
tensor([[0., 0., 0.]])
tensor([[0., 0., 0.]])
