In [1]:
import evolutionary_operator as eo
import torch
import benchmark_funs as bf

In [2]:
problem = bf.Sphere(3)
for i_s in eo.initialization_operators.strategies:
    i_strategy = i_s(problem)
    x = torch.zeros(2, 3)
    h = torch.zeros(2, 4)
    x,h,e = i_strategy(x, h)
    print(x)

tensor([[-62.6376, -93.9308, -63.5702],
        [-69.1540,  61.5717,  -1.8269]])
tensor([[ 12.5326,  14.0513,   4.3649],
        [ 34.5026, -59.2617,  16.6012]])
tensor([[  2.8527,  26.4516,   2.9771],
        [ 19.3569,  15.2643, -15.4786]])
tensor([[ 3.7019, 14.2773,  6.9375],
        [-3.2654, -9.1842,  7.9146]])
tensor([[  5.0547,   3.9718,   0.1288],
        [  6.1003,   1.9989, -76.2149]])
tensor([[-91.6247, -16.0019,  81.7149],
        [ -9.1909, -20.9676,  -9.2374]])
tensor([[ -5.5611,   2.7046,  10.7732],
        [ -0.4360, -38.5832, -10.9815]])
tensor([[20.5423,  0.0000,  0.0000],
        [ 2.7163, 15.1155, 84.3365]])
tensor([[  0.0000,   3.6528, -76.7911],
        [-14.1233,  16.3152,   0.0000]])
tensor([[-30.3826,  12.7547,  20.7891],
        [  0.6666,   1.7915,   0.0000]])
tensor([[ 9.9559,  0.0000,  0.0000],
        [ 0.0000, 23.7168,  0.0000]])


In [3]:
for m_s in eo.mutation_operators.strategies:
    m_strategy = m_s(problem)
    x = torch.zeros(2, 3)
    h = torch.ones(2, 4)
    x,h,e = m_strategy(x, h)
    print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[-0.7726,  0.7744,  0.3707],
        [ 0.6570,  0.7866,  1.9462]])
tensor([[ -7.8490,  -1.4332,  -1.9589],
        [-17.0655,  -0.4681,  -3.4538]])
tensor([[-0.0096,  0.0000,  0.3380],
        [ 0.0000, -0.1994,  0.0000]])
