In [1]:
import evolutionary_operator as eo
import torch
import benchmark_funs as bf

In [3]:
problem = bf.Sphere(3)
for i_s in eo.initialization_operators.strategies:
    i_strategy = i_s(problem)
    x = torch.zeros(2, 3)
    h = torch.zeros(2, 4)
    x,h,e = i_strategy(x, h)
    print(x)

tensor([[-31.6395, -55.1214,  -7.3923],
        [  3.8181,   1.5594,  33.3022]])
tensor([[ -3.6387,  -0.1209,  -4.8264],
        [-14.9334,  40.2682,  21.5897]])
tensor([[ -7.4647, -28.5861,  16.5171],
        [ 10.7942, -29.2277, -15.3646]])
tensor([[  0.0550, -11.0427,  -2.2150],
        [ -3.5085,   7.3761,   7.7148]])
tensor([[ 3.4431e+01, -3.7800e-02,  1.0540e+01],
        [-1.4819e+00,  1.0000e+02, -2.4926e+01]])
tensor([[ 28.0739,  17.2040,  27.6482],
        [-23.5119,  12.6601,   5.8885]])
tensor([[ 1.6217,  1.5776, 15.1564],
        [-2.1444,  0.3696, -2.9136]])
tensor([[   0.0000, -100.0000,   23.2518],
        [   0.0000,    0.0000,   10.6549]])
tensor([[-31.9572,   0.0000,  10.2024],
        [  0.0000,   0.0000,  33.4859]])
tensor([[-57.0832,   0.0000,  -1.5331],
        [  6.6179,   6.8560, -38.3261]])
tensor([[ 9.9558, 64.0351,  0.0000],
        [ 0.0000,  0.0000, -9.3930]])


In [ ]:
eo.mutat