In [1]:
import evolutionary_operator as eo
import torch
import benchmark_funs as bf

In [2]:
problem = bf.Sphere(3)
for i_s in eo.initialization_operators.strategies:
    i_strategy = i_s(problem)
    x = torch.zeros(2, 3)
    h = torch.zeros(2, 4)
    x,h,e = i_strategy(x, h)
    print(x)

tensor([[-56.1873, -94.3073,   3.8274],
        [-16.3273,  90.2293, -35.7021]])
tensor([[-29.0498, -12.6527, -25.0829],
        [ 36.8256,  20.6890,   8.8579]])
tensor([[  7.1885,  -7.1046,  41.8241],
        [-15.9584,  30.2453,  -6.6181]])
tensor([[-17.0168,   2.9200,  10.1768],
        [ -6.4038,   7.1155,  -4.9654]])
tensor([[-9.2364, 41.4823, 10.8730],
        [ 2.4942, -0.8335,  9.3474]])
tensor([[ -4.9961, -14.0637,  18.8914],
        [  8.7283, -30.9772,  24.2210]])
tensor([[ -2.8956,  -3.5182, -28.6496],
        [  8.6641,  -1.2487,  -3.2101]])
tensor([[ -2.5863, -56.6314,   0.0000],
        [ 27.3246,   0.0000,  32.4596]])
tensor([[-23.7716,  26.7809, -10.0969],
        [  0.0000, -32.1293,   0.0000]])
tensor([[5.6373, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
tensor([[  0.0000,  68.6186,   0.0000],
        [ 10.5800, -32.4696,  26.0552]])


In [3]:
for m_s in eo.mutation_operators.strategies:
    m_strategy = m_s(problem)
    x = torch.zeros(2, 3)
    h = torch.ones(2, 4)
    x,h,e = m_strategy(x, h)
    print(x)

tensor([[  0.0000,   0.0000,   0.0000],
        [  0.0000, -19.5178,   0.0000]])
tensor([[-1.2871,  0.5886, -0.2620],
        [ 0.0726, -0.4731, -0.3897]])
tensor([[ 1.0340,  0.4287,  0.6246],
        [-4.8859, -3.8461,  0.3672]])
tensor([[ 0.0000,  0.0000, -0.4359],
        [-0.9403,  0.1685,  0.7236]])


In [4]:
# hh = eo.abstract_operators.hyper_hyper_param_from_dict({'opponents_ratio':3/4})
for s_s in eo.selection_operators.strategies:
    # s_strategy = s_s(problem, hh)
    s_strategy = s_s(problem)
    x = torch.zeros(2, 3)
    h = torch.ones(2, 4)
    x,h,e = s_strategy(x, h)
    print(x)

tensor([[0., 0., 0.]])
tensor([[0., 0., 0.]])
tensor([[0., 0., 0.]])
tensor([[0., 0., 0.]])
tensor([[0., 0., 0.]])
tensor([[0., 0., 0.]])


In [5]:
# hh = eo.abstract_operators.hyper_hyper_param_from_dict({'opponents_ratio':3/4})
for hi_s in eo.hyper_init_operators.strategies:
    hi_strategy = hi_s(problem)
    x = torch.zeros(2, 3)
    h = torch.ones(2, 4)
    x,h,e = hi_strategy(x, h)
    print(h)

tensor([[100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],
        [100.0000,   0.1875,   0.5373,   0.4082],


In [43]:
for hu_s in eo.hyper_update_operators.strategies:
    hu_strategy = hu_s(problem)
    x = torch.zeros(2, 3)
    h = torch.ones(2, 4)*2
    x,h,e = hu_strategy(x, h)
    print(h)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[2.0000, 0.2041, 2.0000, 2.0000],
        [2.0000, 0.0442, 2.0000, 2.0000]])
